### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by azubieta** [azubieta/moolticute#2]
In progress:

Minor stuff:

- [x] Credentials tab: when adding a new credential in the top part and denying the request on the mini, change the "Unable to set credential" to "Couldn't Add New Credential to Device" and empty the text boxes
- [x] When exitting app, a "leave memory management" command should be sent if the mini currently is in memory management mode

Bug fixing:

- [x] device settings tab: if we change the option selected for lock unlock feature and click save, the save & discard buttons do not disappear
- [x] When clicking the download icon for a given file in the file list, entering a file name but denying the request on the mini, the app crashes
- [x] Files Tab: when there are no files on the mini and clicking list files, the list files button is still there. We should instead remove that list files button and add a text "No Files In The Device"
- [x] credentials tab: when going into mmm, accepting the prompt on the mini & entering the pin, press the space bar: something odd will happen
- [x] When compiling Moolticute from source notifications for newer versions still appear: we should therefore disable version checking if version release == git

GUI enhancement:
- [x] credentials tab, in MMM: when clicking the "eye icon" it would be nice to change the "password locked" text to: "Please Approve On Device" and change it back if the request was denied instead of displaying a new window
- [x] Files tab: divide the bottom part in two, and center each part (the list / the files management mode text) on each half. On top of the list, display "Quick File Access" as a title
- [x] Files tab in management mode: select by default the first file (if there's one)
- [x] Files tab in management mode, when one file is selected: center the file name, put the three buttons on top of each other
- [x] Synchronisation tab: Center the complete block, put more space between the texts and the buttons
- [x] It is possible to leave MMM and have errors, but at the moment they aren't displayed to the user. We therefore need to implement this feature as with entering MMM (see cbfailed).

Idiot Proofing:
- [x] in credentials management mode or files management mode and removing the card, we need to remove the warning about tab switching
- [x] when doing import/export/integrity check we need to display a waiting screen to prevent the user form clicking anything
- [x] when an unknown card is inserted (see status) we need to disable the credentials, files, ssh tabs and only enable the "import file" button in the synchronisation tab

Bug report from tester:

-- log is a bit too verbose --

I found a very irritating log issue:

INFO: :0 - "Ask for password for service: arffeh.com:10000 login: fallback_service: reqid: ws-145483127934175389743-19"
WARNING: :0 - Error setting context: 0
CRITICAL: :0 - Failed getting password: "failed to select context on device"
DEBUG: :0 - JSON API recv: {"msg":"ask_password","client_id":21,"data":{"service":"arffeh.com:10000","fallback_service":null,"login":"","request_id":20}}
INFO: :0 - "Ask for password for service: arffeh.com:10000 login: fallback_service: reqid: ws-145483127934175389743-20"
WARNING: :0 - Error setting context: 0
CRITICAL: :0 - Failed getting password: "failed to select context on device"
DEBUG: :0 - JSON API recv: {"msg":"set_credential","data":{"service":"arffeh.com:10000","login":"root","password":"<SNIP>","description":"None"}}

If you try to log in while the mooltipass is in management mode or for whatever reason communication fails, it just blasts your password all-over the log. While I can appreciate a detailed logfile, sanitizing logs for a security device is probably ideal.
