### ISSUE TITLE
TODO 2

### ISSUE THREAD

**Issue by azubieta** [azubieta/moolticute#3]
- [x] when denying the data sending prompt on the mini, can you change the message to: "Data Fetch Denied" instead of "Data sending was denied", in your quick list access, when you click the download icon but deny the request on the mini
- [x] credentials tab, in MMM: when clicking the "eye icon" it would be nice to change the "password locked" text to: "Please Approve On Device" and change it back if the request was denied instead of displaying a new window >> Could you change the message to "Password Query Was Denied" instead of "Unable to query password!"

- [x] buttons in the files managemetn mode less wide

- [x] re-enable tab switching warnigns but checking that is only shown when we are in MMM
